assert = @(x) x || throw Throwable("Assertion failed."
nata = Module("nata"
testing = Module("testing"
test = testing.test

nata.main(@ test("builtin map C", "abcdefghi", @(vi, type, update)
	assert(vi.buffer().view.position__(3, false
	type("C"
	assert(update() == "INSERT 1,4-4 100% <0?2> "
	assert(vi.buffer().view.text.slice(0, -1) == "abc"

nata.main(@ test("builtin map s", "abcdefghi", @(vi, type, update)
	assert(vi.buffer().view.position__(3, false
	type("2s"
	assert(update() == "INSERT 1,4-4 100% <0?2> "
	assert(vi.buffer().view.text.slice(0, -1) == "abcfghi"

nata.main(@ test("map", "abcdefghi", @(vi, type, update)
	type(":"
	assert(update() == ":"
	type("map __ l."
	assert(update() == ":map __ l."
	type("^M"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type(":map _ya iYAH!^M"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type("_ya"
	assert(update() == "INSERT 1,5-5 100% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == "YAH!abcdefghi"
	type("^["
	assert(update() == "NORMAL 1,5-5 100% <1>* "
	type("_"
	assert(update() == "NORMAL 1,5-5 100% <1>* _ t1000"
	type("_"
	assert(update() == "NORMAL 1,10-10 100% <2>* "
	assert(vi.buffer().text.slice(0, -1) == "YAH!aYAH!bcdefghi"
	type(":map^M"
	assert(update() == "maps <buffer>\nmaps\n nvo\t__\t l.\n nvo\t_ya\t iYAH!"
	type(":unmap __^M:map^M"
	assert(update() == "maps <buffer>\nmaps\n nvo\t_ya\t iYAH!"
	type(":unmap _ya^M:map^M"
	assert(update() == "maps <buffer>\nmaps"

nata.main(@ test("map timeout", "abc", @(vi, type, update)
	type(":map ll $^M"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type("l"
	assert(update() == "NORMAL 1,1-1 100% <0> l t1000"
	type(String.from_code(0
	assert(update() == "NORMAL 1,2-2 100% <0> "
	type("l"
	assert(update() == "NORMAL 1,2-2 100% <0> l t1000"
	type("l"
	assert(update() == "NORMAL 1,4-4 100% <0> "

nata.main(@ test("map ambiguous", "abc", @(vi, type, update)
	type(":map _ $^M"
	type(":map _, l^M"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type("_"
	assert(update() == "NORMAL 1,1-1 100% <0> _ t1000"
	type(","
	assert(update() == "NORMAL 1,2-2 100% <0> "
	type("_"
	assert(update() == "NORMAL 1,2-2 100% <0> _ t1000"
	type(String.from_code(0
	assert(update() == "NORMAL 1,4-4 100% <0> "

nata.main(@ test("map ambiguous operator pending", "abcdefghi", @(vi, type, update)
	type(":map c, 3l^M"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type("c"
	assert(update() == "NORMAL 1,1-1 100% <0> c t1000"
	type(","
	assert(update() == "NORMAL 1,4-4 100% <0> "
	type("cc"
	assert(update() == "NORMAL 1,4-4 100% <0> cc t1000"
	type(","
	assert(update() == "INSERT 1,4-4 100% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == "abcghi"

nata.main(@ test("noremap", "abcdefghi", @(vi, type, update)
	type(":noremap h l^M"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type(":noremap l h^M"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type("h"
	assert(update() == "NORMAL 1,2-2 100% <0> "
	type("l"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type("3c2h"
	assert(update() == "INSERT 1,1-1 100% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == "ghi"

nata.main(@ test("noremap!", "", @(vi, type, update)
	type(":noremap! A a^M:map! a b^M"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type(":noremAp! b Abc^M"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type("2ia"
	assert(update() == "INSERT 1,4-4 100% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == "abc"
	type("^["
	assert(update() == "NORMAL 1,7-7 100% <1>* "
	assert(vi.buffer().text.slice(0, -1) == "abcabc"
	type("3."
	assert(update() == "NORMAL 1,16-16 100% <2>* "
	assert(vi.buffer().text.slice(0, -1) == "abcabcabcabcabc"

nata.main(@ test("map <buffer>", "abcdefghi", @(vi, type, update)
	type(":map <buffer> __ l.^M"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type(":map _ya iYAH!^M"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type("_ya^["
	assert(update() == "NORMAL 1,5-5 100% <1>* "
	assert(vi.buffer().text.slice(0, -1) == "YAH!abcdefghi"
	type("__"
	assert(update() == "NORMAL 1,10-10 100% <2>* "
	assert(vi.buffer().text.slice(0, -1) == "YAH!aYAH!bcdefghi"
	type(":map^M"
	assert(update() == "maps <buffer>\n nvo\t__\t l.\nmaps\n nvo\t_ya\t iYAH!"
	type(":unmap _ya^M:map^M"
	assert(update() == "maps <buffer>\n nvo\t__\t l.\nmaps"
	type(":unmap <buffer> __^M:map^M"
	assert(update() == "maps <buffer>\nmaps"
