assert = @(x) x || throw Throwable("Assertion failed."
nata = Module("nata"
testing = Module("testing"
test = testing.test

nata.main(@ test("insert", null, @(vi, type, update)
	type("2"
	assert(update() == "NORMAL 1,1-1 100% <0> 2"
	type("i"
	assert(update() == "INSERT 1,1-1 100% <0> "
	type("h"
	assert(update() == "INSERT 1,2-2 100% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == "h"
	type("e"
	assert(update() == "INSERT 1,3-3 100% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == "he"
	type("^H"
	assert(update() == "INSERT 1,2-2 100% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == "h"
	type("i"
	assert(update() == "INSERT 1,3-3 100% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == "hi"
	type("^["
	assert(update() == "NORMAL 1,5-5 100% <1>* "
	assert(vi.buffer().text.slice(0, -1) == "hihi"
	type("u"
	assert(update() == "NORMAL 1,1-1 100% <0|1> "
	assert(vi.buffer().text.slice(0, -1) == ""
	type("^R"
	assert(update() == "NORMAL 1,5-5 100% <1>* "
	assert(vi.buffer().text.slice(0, -1) == "hihi"
	type("."
	assert(update() == "NORMAL 1,9-9 100% <2>* "
	assert(vi.buffer().text.slice(0, -1) == "hihihihi"
	type("3."
	assert(update() == "NORMAL 1,15-15 100% <3>* "
	assert(vi.buffer().text.slice(0, -1) == "hihihihihihihi"

nata.main(@ test("insert literally", "", @(vi, type, update)
	type("3i^V"
	assert(update() == "INSERT 1,1-1 100% <0> ^V"
	assert(vi.buffer().text.slice(0, -1) == ""
	type("^["
	assert(update() == "INSERT 1,2-2 100% <0?2> "
	E = String.from_code(0x1b
	assert(vi.buffer().text.slice(0, -1) == E
	type("^["
	assert(update() == "NORMAL 1,4-4 100% <1>* "
	assert(vi.buffer().text.slice(0, -1) == E + E + E
	type("2."
	assert(update() == "NORMAL 1,6-6 100% <2>* "
	assert(vi.buffer().text.slice(0, -1) == E + E + E + E + E

nata.main(@ test("insert by decimal digits", "", @(vi, type, update)
	type("3i^V03"
	assert(update() == "INSERT 1,1-1 100% <0> ^V03"
	assert(vi.buffer().text.slice(0, -1) == ""
	type("2"
	assert(update() == "INSERT 1,2-2 100% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == " "
	type("^["
	assert(update() == "NORMAL 1,4-4 100% <1>* "
	assert(vi.buffer().text.slice(0, -1) == "   "
	type("2."
	assert(update() == "NORMAL 1,6-6 100% <2>* "
	assert(vi.buffer().text.slice(0, -1) == "     "

nata.main(@ test("insert by decimal digits followed by non digit", "", @(vi, type, update)
	type("3i^V33"
	assert(update() == "INSERT 1,1-1 100% <0> ^V33"
	assert(vi.buffer().text.slice(0, -1) == ""
	type("a"
	assert(update() == "INSERT 1,3-3 100% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == "!a"
	type("^["
	assert(update() == "NORMAL 1,7-7 100% <1>* "
	assert(vi.buffer().text.slice(0, -1) == "!a!a!a"
	type("2."
	assert(update() == "NORMAL 1,11-11 100% <2>* "
	assert(vi.buffer().text.slice(0, -1) == "!a!a!a!a!a"

nata.main(@ test("insert by octal digits", "", @(vi, type, update)
	type("i^Vo04"
	assert(update() == "INSERT 1,1-1 100% <0> ^Vo04"
	assert(vi.buffer().text.slice(0, -1) == ""
	type("2"
	assert(update() == "INSERT 1,2-2 100% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == "\""

nata.main(@ test("insert by octal digits followed by non digit", "", @(vi, type, update)
	type("i^Vo43"
	assert(update() == "INSERT 1,1-1 100% <0> ^Vo43"
	assert(vi.buffer().text.slice(0, -1) == ""
	type("8"
	assert(update() == "INSERT 1,3-3 100% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == "#8"

nata.main(@ test("insert by hexadecimal digits", "", @(vi, type, update)
	type("i^Vx2"
	assert(update() == "INSERT 1,1-1 100% <0> ^Vx2"
	assert(vi.buffer().text.slice(0, -1) == ""
	type("4"
	assert(update() == "INSERT 1,2-2 100% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == "$"

nata.main(@ test("insert by hexadecimal digits followed by non digit", "", @(vi, type, update)
	type("i^Vxf"
	assert(update() == "INSERT 1,1-1 100% <0> ^Vxf"
	assert(vi.buffer().text.slice(0, -1) == ""
	type("g"
	assert(update() == "INSERT 1,3-3 100% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == String.from_code(0xf) + "g"

nata.main(@ test("I inserts text before the first no-blank in the line", " 0", @(vi, type, update)
	type("I"
	assert(update() == "INSERT 1,2-2 100% <0> "
	assert(vi.buffer().text.slice(0, -1) == " 0"
	type("a"
	assert(update() == "INSERT 1,3-3 100% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == " a0"
	type("^["
	assert(update() == "NORMAL 1,3-3 100% <1>* "
	assert(vi.buffer().text.slice(0, -1) == " a0"
	type("3I"
	assert(update() == "INSERT 1,2-2 100% <1>* "
	assert(vi.buffer().text.slice(0, -1) == " a0"
	type("b"
	assert(update() == "INSERT 1,3-3 100% <1?2>* "
	assert(vi.buffer().text.slice(0, -1) == " ba0"
	type("^["
	assert(update() == "NORMAL 1,5-5 100% <2>* "
	assert(vi.buffer().text.slice(0, -1) == " bbba0"

nata.main(@ test("a appends text after the cursor", "01", @(vi, type, update)
	type("a"
	assert(update() == "INSERT 1,2-2 100% <0> "
	assert(vi.buffer().text.slice(0, -1) == "01"
	type("a"
	assert(update() == "INSERT 1,3-3 100% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == "0a1"
	type("^["
	assert(update() == "NORMAL 1,3-3 100% <1>* "
	assert(vi.buffer().text.slice(0, -1) == "0a1"
	type("3a"
	assert(update() == "INSERT 1,4-4 100% <1>* "
	assert(vi.buffer().text.slice(0, -1) == "0a1"
	type("b"
	assert(update() == "INSERT 1,5-5 100% <1?2>* "
	assert(vi.buffer().text.slice(0, -1) == "0a1b"
	type("^["
	assert(update() == "NORMAL 1,7-7 100% <2>* "
	assert(vi.buffer().text.slice(0, -1) == "0a1bbb"

nata.main(@ test("A appends text at the end of the line", "01", @(vi, type, update)
	type("A"
	assert(update() == "INSERT 1,3-3 100% <0> "
	assert(vi.buffer().text.slice(0, -1) == "01"
	type("a^M"
	assert(update() == "INSERT 2,1-1 0% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == "01a\n"
	type("^["
	assert(update() == "NORMAL 2,1-1 0% <1>* "
	assert(vi.buffer().text.slice(0, -1) == "01a\n"
	type("k3A"
	assert(update() == "INSERT 1,4-4 0% <1>* "
	assert(vi.buffer().text.slice(0, -1) == "01a\n"
	type("b"
	assert(update() == "INSERT 1,5-5 0% <1?2>* "
	assert(vi.buffer().text.slice(0, -1) == "01ab\n"
	type("^["
	assert(update() == "NORMAL 1,7-7 0% <2>* "
	assert(vi.buffer().text.slice(0, -1) == "01abbb\n"

nata.main(@ test("o begins a new line below the cursor", "0\n1", @(vi, type, update)
	type("o"
	assert(update() == "INSERT 2,1-1 0% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == "0\n\n1"
	type("a"
	assert(update() == "INSERT 2,2-2 0% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == "0\na\n1"
	type("^["
	assert(update() == "NORMAL 2,2-2 0% <1>* "
	assert(vi.buffer().text.slice(0, -1) == "0\na\n1"
	type("3o"
	assert(update() == "INSERT 3,1-1 0% <1?2>* "
	assert(vi.buffer().text.slice(0, -1) == "0\na\n\n1"
	type("bc"
	assert(update() == "INSERT 3,3-3 0% <1?2>* "
	assert(vi.buffer().text.slice(0, -1) == "0\na\nbc\n1"
	type("^["
	assert(update() == "NORMAL 5,3-3 0% <2>* "
	assert(vi.buffer().text.slice(0, -1) == "0\na\nbc\nbc\nbc\n1"
	type("jo"
	assert(update() == "out of range."
	assert(vi.buffer().text.slice(0, -1) == "0\na\nbc\nbc\nbc\n1"

nata.main(@ test("O begins a new line above the cursor", "0\n1", @(vi, type, update)
	type("O"
	assert(update() == "INSERT 1,1-1 0% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == "\n0\n1"
	type("a"
	assert(update() == "INSERT 1,2-2 0% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == "a\n0\n1"
	type("^["
	assert(update() == "NORMAL 1,2-2 0% <1>* "
	assert(vi.buffer().text.slice(0, -1) == "a\n0\n1"
	type("2j3O"
	assert(update() == "INSERT 3,1-1 0% <1?2>* "
	assert(vi.buffer().text.slice(0, -1) == "a\n0\n\n1"
	type("bc"
	assert(update() == "INSERT 3,3-3 0% <1?2>* "
	assert(vi.buffer().text.slice(0, -1) == "a\n0\nbc\n1"
	type("^["
	assert(update() == "NORMAL 5,3-3 0% <2>* "
	assert(vi.buffer().text.slice(0, -1) == "a\n0\nbc\nbc\nbc\n1"
