assert = @(x) x || throw Throwable("Assertion failed."
nata = Module("nata"
testing = Module("testing"
test = testing.test

nata.main(@ test("h/l moves to the left/right", "abc", @(vi, type, update)
	type("lll"
	assert(update() == "NORMAL 1,4-4 100% <0> "
	type("hhh"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type("2l"
	assert(update() == "NORMAL 1,3-3 100% <0> "
	type("2h"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type("4l"
	assert(update() == "NORMAL 1,4-4 100% <0> "
	type("4h"
	assert(update() == "NORMAL 1,1-1 100% <0> "

nata.main(@ test("just 0 moves to the head", "abc", @(vi, type, update)
	type("lll"
	assert(update() == "NORMAL 1,4-4 100% <0> "
	type("0"
	assert(update() == "NORMAL 1,1-1 100% <0> "

nata.main(@ test("^ moves to the first non-blank", " abc", @(vi, type, update)
	type("^^"
	assert(update() == "NORMAL 1,2-2 100% <0> "
	type("lll"
	assert(update() == "NORMAL 1,5-5 100% <0> "
	type("3^^"
	assert(update() == "NORMAL 1,2-2 100% <0> "

nata.main(@ test("$ moves to the end of line", "abc\nabcd\nabcde\nabcdef", @(vi, type, update)
	type("$"
	assert(update() == "NORMAL 1,4-4 100% <0> "
	type("0"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type("3$"
	assert(update() == "NORMAL 3,6-6 100% <0> "
	type("0"
	assert(update() == "NORMAL 3,1-1 100% <0> "
	type("3$"
	assert(update() == "NORMAL 4,7-7 100% <0> "

nata.main(@ test("| moves to screen column", "abc", @(vi, type, update)
	type("3|"
	assert(update() == "NORMAL 1,3-3 100% <0> "
	type("|"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type("5|"
	assert(update() == "NORMAL 1,4-4 100% <0> "

nata.main(@ test("f moves to the occurrence to the right", "abcabcabc", @(vi, type, update)
	type("fa"
	assert(update() == "NORMAL 1,4-4 100% <0> "
	type("fa"
	assert(update() == "NORMAL 1,7-7 100% <0> "
	type("0"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type("fb"
	assert(update() == "NORMAL 1,2-2 100% <0> "
	type("3fb"
	assert(update() == "NORMAL 1,2-2 100% <0> "
	type("2fb"
	assert(update() == "NORMAL 1,8-8 100% <0> "

nata.main(@ test("F moves to the occurrence to the left", "abcabcabc", @(vi, type, update)
	type("8 "
	assert(update() == "NORMAL 1,9-9 100% <0> "
	type("Fc"
	assert(update() == "NORMAL 1,6-6 100% <0> "
	type("Fc"
	assert(update() == "NORMAL 1,3-3 100% <0> "
	type("$"
	assert(update() == "NORMAL 1,10-10 100% <0> "
	type("Fb"
	assert(update() == "NORMAL 1,8-8 100% <0> "
	type("3Fb"
	assert(update() == "NORMAL 1,8-8 100% <0> "
	type("2Fb"
	assert(update() == "NORMAL 1,2-2 100% <0> "

nata.main(@ test("; repeats the latest f or F", "abcabcabc", @(vi, type, update)
	type(";"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type("fb0"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type(";"
	assert(update() == "NORMAL 1,2-2 100% <0> "
	type("2;"
	assert(update() == "NORMAL 1,8-8 100% <0> "

nata.main(@ test(", repeats the latest f or F in opposite direction", "abcabcabc", @(vi, type, update)
	type("$"
	assert(update() == "NORMAL 1,10-10 100% <0> "
	type(","
	assert(update() == "NORMAL 1,10-10 100% <0> "
	type("fc"
	assert(update() == "NORMAL 1,10-10 100% <0> "
	type(","
	assert(update() == "NORMAL 1,9-9 100% <0> "
	type("2,"
	assert(update() == "NORMAL 1,3-3 100% <0> "
