assert = @(x) x || throw Throwable("Assertion failed."
nata = Module("nata"
testing = Module("testing"
test = testing.test

nata.main(@ test("delete motion", "abcdefghijklmnopqr", @(vi, type, update)
	type("2d3"
	assert(update() == "NORMAL 1,1-1 100% <0> 2d3"
	type("l"
	assert(update() == "NORMAL 1,1-1 100% <1> "
	assert(vi.buffer().text.slice(0, -1) == "ghijklmnopqr"
	type("u"
	assert(update() == "NORMAL 1,1-1 100% <0|1> "
	assert(vi.buffer().text.slice(0, -1) == "abcdefghijklmnopqr"
	type("^R"
	assert(update() == "NORMAL 1,1-1 100% <1> "
	assert(vi.buffer().text.slice(0, -1) == "ghijklmnopqr"
	type("3."
	assert(update() == "NORMAL 1,1-1 100% <2> "
	assert(vi.buffer().text.slice(0, -1) == "pqr"

nata.main(@ test("change motion", "abcdefghijklmnopqr", @(vi, type, update)
	type("2c3l"
	assert(update() == "INSERT 1,1-1 100% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == "ghijklmnopqr"
	type("ABC"
	assert(update() == "INSERT 1,4-4 100% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == "ABCghijklmnopqr"
	type("^["
	assert(update() == "NORMAL 1,4-4 100% <1> "
	assert(vi.buffer().text.slice(0, -1) == "ABCghijklmnopqr"
	type("u"
	assert(update() == "NORMAL 1,1-1 100% <0|1> "
	assert(vi.buffer().text.slice(0, -1) == "abcdefghijklmnopqr"
	type("^R"
	assert(update() == "NORMAL 1,4-4 100% <1> "
	assert(vi.buffer().text.slice(0, -1) == "ABCghijklmnopqr"
	type("3."
	assert(update() == "NORMAL 1,7-7 100% <2> "
	assert(vi.buffer().text.slice(0, -1) == "ABCABCpqr"

nata.main(@ test("yank motion & paste", "abcdefghijklmnopqr", @(vi, type, update)
	type("3y2l"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type("2p"
	assert(update() == "NORMAL 1,13-13 100% <1> "
	assert(vi.buffer().text.slice(0, -1) == "abcdefabcdefabcdefghijklmnopqr"
	type("u"
	assert(update() == "NORMAL 1,1-1 100% <0|1> "
	assert(vi.buffer().text.slice(0, -1) == "abcdefghijklmnopqr"
	type("^R"
	assert(update() == "NORMAL 1,13-13 100% <1> "
	assert(vi.buffer().text.slice(0, -1) == "abcdefabcdefabcdefghijklmnopqr"
	type("3."
	assert(update() == "NORMAL 1,31-31 100% <2> "
	assert(vi.buffer().text.slice(0, -1) == "abcdefabcdefabcdefabcdefabcdefabcdefghijklmnopqr"

nata.main(@ test("delete lines", "abc\ndef\nghi\njkl\nmno\npqr", @(vi, type, update)
	type("2dd"
	assert(update() == "NORMAL 1,1-1 100% <1> "
	assert(vi.buffer().text.slice(0, -1) == "ghi\njkl\nmno\npqr"
	type("u"
	assert(update() == "NORMAL 1,1-1 100% <0|1> "
	assert(vi.buffer().text.slice(0, -1) == "abc\ndef\nghi\njkl\nmno\npqr"
	type("^R"
	assert(update() == "NORMAL 1,1-1 100% <1> "
	assert(vi.buffer().text.slice(0, -1) == "ghi\njkl\nmno\npqr"
	type("3."
	assert(update() == "NORMAL 1,1-1 100% <2> "
	assert(vi.buffer().text.slice(0, -1) == "pqr"

nata.main(@ test("change lines", "abc\ndef\nghi\njkl\nmno\npqr", @(vi, type, update)
	type("2cc"
	assert(update() == "INSERT 1,1-1 100% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == "\nghi\njkl\nmno\npqr"
	type("ABC"
	assert(update() == "INSERT 1,4-4 100% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == "ABC\nghi\njkl\nmno\npqr"
	type("^["
	assert(update() == "NORMAL 1,4-4 100% <1> "
	assert(vi.buffer().text.slice(0, -1) == "ABC\nghi\njkl\nmno\npqr"
	type("u"
	assert(update() == "NORMAL 1,1-1 100% <0|1> "
	assert(vi.buffer().text.slice(0, -1) == "abc\ndef\nghi\njkl\nmno\npqr"
	type("^R"
	assert(update() == "NORMAL 1,4-4 100% <1> "
	assert(vi.buffer().text.slice(0, -1) == "ABC\nghi\njkl\nmno\npqr"
	type("3."
	assert(update() == "NORMAL 1,4-4 100% <2> "
	assert(vi.buffer().text.slice(0, -1) == "ABC\nmno\npqr"

nata.main(@ test("yank lines & paste", "abc\ndef\nghi\njkl\nmno\npqr", @(vi, type, update)
	type("2yy"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type("2p"
	assert(update() == "NORMAL 5,1-1 100% <1> "
	assert(vi.buffer().text.slice(0, -1) == "abc\ndef\nabc\ndef\nabc\ndef\nghi\njkl\nmno\npqr"
	type("u"
	assert(update() == "NORMAL 1,1-1 100% <0|1> "
	assert(vi.buffer().text.slice(0, -1) == "abc\ndef\nghi\njkl\nmno\npqr"
	type("^R"
	assert(update() == "NORMAL 5,1-1 100% <1> "
	assert(vi.buffer().text.slice(0, -1) == "abc\ndef\nabc\ndef\nabc\ndef\nghi\njkl\nmno\npqr"
	type("3."
	assert(update() == "NORMAL 11,1-1 100% <2> "
	assert(vi.buffer().text.slice(0, -1) == "abc\ndef\nabc\ndef\nabc\ndef\nabc\ndef\nabc\ndef\nabc\ndef\nghi\njkl\nmno\npqr"

nata.main(@ test("delete selection", "abcdefghi", @(vi, type, update)
	type("v3l"
	assert(update() == "VISUAL 1,4-4 100% <0> "
	type("d"
	assert(update() == "NORMAL 1,1-1 100% <1> "
	assert(vi.buffer().text.slice(0, -1) == "defghi"
	type("u"
	assert(update() == "NORMAL 1,1-1 100% <0|1> "
	assert(vi.buffer().text.slice(0, -1) == "abcdefghi"
	type("^R"
	assert(update() == "NORMAL 1,1-1 100% <1> "
	assert(vi.buffer().text.slice(0, -1) == "defghi"
	type("3."
	assert(update() == "NORMAL 1,1-1 100% <2> "
	assert(vi.buffer().text.slice(0, -1) == "ghi"

nata.main(@ test("change selection", "abcdefghi", @(vi, type, update)
	type("v3l"
	assert(update() == "VISUAL 1,4-4 100% <0> "
	type("c"
	assert(update() == "INSERT 1,1-1 100% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == "defghi"
	type("ABC"
	assert(update() == "INSERT 1,4-4 100% <0?2> "
	assert(vi.buffer().text.slice(0, -1) == "ABCdefghi"
	type("^["
	assert(update() == "NORMAL 1,4-4 100% <1> "
	assert(vi.buffer().text.slice(0, -1) == "ABCdefghi"
	type("u"
	assert(update() == "NORMAL 1,1-1 100% <0|1> "
	assert(vi.buffer().text.slice(0, -1) == "abcdefghi"
	type("^R"
	assert(update() == "NORMAL 1,4-4 100% <1> "
	assert(vi.buffer().text.slice(0, -1) == "ABCdefghi"
	type("3."
	assert(update() == "NORMAL 1,7-7 100% <2> "
	assert(vi.buffer().text.slice(0, -1) == "ABCABCghi"

nata.main(@ test("yank selection & paste", "abcdefghi", @(vi, type, update)
	type("v3l"
	assert(update() == "VISUAL 1,4-4 100% <0> "
	type("y"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type("2p"
	assert(update() == "NORMAL 1,7-7 100% <1> "
	assert(vi.buffer().text.slice(0, -1) == "abcabcabcdefghi"
	type("u"
	assert(update() == "NORMAL 1,1-1 100% <0|1> "
	assert(vi.buffer().text.slice(0, -1) == "abcdefghi"
	type("^R"
	assert(update() == "NORMAL 1,7-7 100% <1> "
	assert(vi.buffer().text.slice(0, -1) == "abcabcabcdefghi"
	type("3."
	assert(update() == "NORMAL 1,16-16 100% <2> "
	assert(vi.buffer().text.slice(0, -1) == "abcabcabcabcabcabcdefghi"
