assert = @(x) x || throw Throwable("Assertion failed."
nata = Module("nata"
testing = Module("testing"
test = testing.test

nata.main(@ test("h/l moves to the left/right", "abc", @(vi, type, update)
	type("lll"
	assert(update() == "NORMAL 1,4-4 100% <0> "
	type("hhh"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type("2l"
	assert(update() == "NORMAL 1,3-3 100% <0> "
	type("2h"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type("4l"
	assert(update() == "NORMAL 1,4-4 100% <0> "
	type("4h"
	assert(update() == "NORMAL 1,1-1 100% <0> "

nata.main(@ test("just 0 moves to the head", "abc", @(vi, type, update)
	type("lll"
	assert(update() == "NORMAL 1,4-4 100% <0> "
	type("0"
	assert(update() == "NORMAL 1,1-1 100% <0> "

nata.main(@ test("^ moves to the first non-blank", " abc", @(vi, type, update)
	type("^^"
	assert(update() == "NORMAL 1,2-2 100% <0> "
	type("lll"
	assert(update() == "NORMAL 1,5-5 100% <0> "
	type("3^^"
	assert(update() == "NORMAL 1,2-2 100% <0> "

nata.main(@ test("$ moves to the end of line", "abc\nabcd\nabcde\nabcdef", @(vi, type, update)
	type("$"
	assert(update() == "NORMAL 1,4-4 0% <0> "
	type("0"
	assert(update() == "NORMAL 1,1-1 0% <0> "
	type("3$"
	assert(update() == "NORMAL 3,6-6 0% <0> "
	type("0"
	assert(update() == "NORMAL 3,1-1 0% <0> "
	type("3$"
	assert(update() == "NORMAL 4,7-7 0% <0> "

nata.main(@ test("| moves to screen column", "abc", @(vi, type, update)
	type("3|"
	assert(update() == "NORMAL 1,3-3 100% <0> "
	type("|"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type("5|"
	assert(update() == "NORMAL 1,4-4 100% <0> "

nata.main(@ test("f moves to the occurrence to the right", "abcabcabc", @(vi, type, update)
	type("fa"
	assert(update() == "NORMAL 1,4-4 100% <0> "
	type("fa"
	assert(update() == "NORMAL 1,7-7 100% <0> "
	type("0"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type("fb"
	assert(update() == "NORMAL 1,2-2 100% <0> "
	type("3fb"
	assert(update() == "NORMAL 1,2-2 100% <0> "
	type("2fb"
	assert(update() == "NORMAL 1,8-8 100% <0> "

nata.main(@ test("F moves to the occurrence to the left", "abcabcabc", @(vi, type, update)
	type("8 "
	assert(update() == "NORMAL 1,9-9 100% <0> "
	type("Fc"
	assert(update() == "NORMAL 1,6-6 100% <0> "
	type("Fc"
	assert(update() == "NORMAL 1,3-3 100% <0> "
	type("$"
	assert(update() == "NORMAL 1,10-10 100% <0> "
	type("Fb"
	assert(update() == "NORMAL 1,8-8 100% <0> "
	type("3Fb"
	assert(update() == "NORMAL 1,8-8 100% <0> "
	type("2Fb"
	assert(update() == "NORMAL 1,2-2 100% <0> "

nata.main(@ test("; repeats the latest f or F", "abcabcabc", @(vi, type, update)
	type(";"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type("fb0"
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type(";"
	assert(update() == "NORMAL 1,2-2 100% <0> "
	type("2;"
	assert(update() == "NORMAL 1,8-8 100% <0> "

nata.main(@ test(", repeats the latest f or F in opposite direction", "abcabcabc", @(vi, type, update)
	type("$"
	assert(update() == "NORMAL 1,10-10 100% <0> "
	type(","
	assert(update() == "NORMAL 1,10-10 100% <0> "
	type("fc"
	assert(update() == "NORMAL 1,10-10 100% <0> "
	type(","
	assert(update() == "NORMAL 1,9-9 100% <0> "
	type("2,"
	assert(update() == "NORMAL 1,3-3 100% <0> "

nata.main(@ test("k/j moves upward/downward", "abc\nabc\na\nabcd", @(vi, type, update)
	type("3l"
	assert(update() == "NORMAL 1,4-4 0% <0> "
	type("jjj"
	assert(update() == "NORMAL 4,4-4 0% <0> "
	type("kkk"
	assert(update() == "NORMAL 1,4-4 0% <0> "
	type("2j"
	assert(update() == "NORMAL 3,2-2 0% <0> "
	type("2k"
	assert(update() == "NORMAL 1,4-4 0% <0> "
	type("4j"
	assert(update() == "NORMAL 4,4-4 0% <0> "
	type("4k"
	assert(update() == "NORMAL 1,4-4 0% <0> "

nata.main(@ test("-/+ moves upward/downward on the first non-blank", "\tabc\n  abc\n   \n abc", @(vi, type, update)
	type("+"
	assert(update() == "NORMAL 2,3-3 0% <0> "
	type("2+"
	assert(update() == "NORMAL 4,2-2 0% <0> "
	type("-"
	assert(update() == "NORMAL 3,4-4 0% <0> "
	type("2-"
	assert(update() == "NORMAL 1,2-2 0% <0> "
	type("4+"
	assert(update() == "NORMAL 4,2-2 0% <0> "
	type("l"
	assert(update() == "NORMAL 4,3-3 0% <0> "
	type("+"
	assert(update() == "NORMAL 4,3-3 0% <0> "
	type("4-"
	assert(update() == "NORMAL 1,2-2 0% <0> "
	type("l"
	assert(update() == "NORMAL 1,3-3 0% <0> "
	type("-"
	assert(update() == "NORMAL 1,3-3 0% <0> "

nata.main(@ test("G gotos line on the first non-blank", "\tabc\n  abc\n   \n abc", @(vi, type, update)
	type("2G"
	assert(update() == "NORMAL 2,3-3 0% <0> "
	type("5G"
	assert(update() == "NORMAL 4,2-2 0% <0> "
	type("3G"
	assert(update() == "NORMAL 3,4-4 0% <0> "
	type("1G"
	assert(update() == "NORMAL 1,2-2 0% <0> "
	type("G"
	assert(update() == "NORMAL 4,2-2 0% <0> "

nata.main(@ test("gg gotos line on the first non-blank", "\tabc\n  abc\n   \n abc", @(vi, type, update)
	type("2gg"
	assert(update() == "NORMAL 2,3-3 0% <0> "
	type("5gg"
	assert(update() == "NORMAL 4,2-2 0% <0> "
	type("1gg"
	assert(update() == "NORMAL 1,2-2 0% <0> "
	type("3gg"
	assert(update() == "NORMAL 3,4-4 0% <0> "
	type("gg"
	assert(update() == "NORMAL 1,2-2 0% <0> "

nata.main(@ test("w moves count words forward", "abc() abc\t()\n\nabc", @(vi, type, update)
	type("w"
	assert(update() == "NORMAL 1,4-4 0% <0> "
	type("w"
	assert(update() == "NORMAL 1,7-7 0% <0> "
	type("w"
	assert(update() == "NORMAL 1,11-11 0% <0> "
	type("w"
	assert(update() == "NORMAL 2,1-1 0% <0> "
	type("w"
	assert(update() == "NORMAL 3,1-1 0% <0> "
	type("w"
	assert(update() == "NORMAL 3,4-4 0% <0> "
	type("w"
	assert(update() == "NORMAL 3,4-4 0% <0> "
	assert(vi.buffer().view.position__(0, false
	assert(update() == "NORMAL 1,1-1 0% <0> "
	type("2w"
	assert(update() == "NORMAL 1,7-7 0% <0> "
	type("2w"
	assert(update() == "NORMAL 2,1-1 0% <0> "
	type("3w"
	assert(update() == "NORMAL 3,4-4 0% <0> "

nata.main(@ test("W moves count WORDS forward", "abc() abc\t()\n\n(abc)", @(vi, type, update)
	type("W"
	assert(update() == "NORMAL 1,7-7 0% <0> "
	type("W"
	assert(update() == "NORMAL 1,11-11 0% <0> "
	type("W"
	assert(update() == "NORMAL 2,1-1 0% <0> "
	type("W"
	assert(update() == "NORMAL 3,1-1 0% <0> "
	type("W"
	assert(update() == "NORMAL 3,6-6 0% <0> "
	type("W"
	assert(update() == "NORMAL 3,6-6 0% <0> "
	assert(vi.buffer().view.position__(0, false
	assert(update() == "NORMAL 1,1-1 0% <0> "
	type("2W"
	assert(update() == "NORMAL 1,11-11 0% <0> "
	type("2W"
	assert(update() == "NORMAL 3,1-1 0% <0> "
	type("3W"
	assert(update() == "NORMAL 3,6-6 0% <0> "

nata.main(@ test("e moves forward to the end of word", "abc() abc\t()\n\nabc", @(vi, type, update)
	type("e"
	assert(update() == "NORMAL 1,4-4 0% <0> "
	type("e"
	assert(update() == "NORMAL 1,6-6 0% <0> "
	type("e"
	assert(update() == "NORMAL 1,10-10 0% <0> "
	type("e"
	assert(update() == "NORMAL 1,13-13 0% <0> "
	type("e"
	assert(update() == "NORMAL 3,4-4 0% <0> "
	type("e"
	assert(update() == "NORMAL 3,4-4 0% <0> "
	assert(vi.buffer().view.position__(0, false
	assert(update() == "NORMAL 1,1-1 0% <0> "
	type("2e"
	assert(update() == "NORMAL 1,6-6 0% <0> "
	type("2e"
	assert(update() == "NORMAL 1,13-13 0% <0> "
	type("2e"
	assert(update() == "NORMAL 3,4-4 0% <0> "

nata.main(@ test("E moves forward to the end of WORD", "abc() abc\t()\n\n(abc)", @(vi, type, update)
	type("E"
	assert(update() == "NORMAL 1,6-6 0% <0> "
	type("E"
	assert(update() == "NORMAL 1,10-10 0% <0> "
	type("E"
	assert(update() == "NORMAL 1,13-13 0% <0> "
	type("E"
	assert(update() == "NORMAL 3,6-6 0% <0> "
	type("E"
	assert(update() == "NORMAL 3,6-6 0% <0> "
	assert(vi.buffer().view.position__(0, false
	assert(update() == "NORMAL 1,1-1 0% <0> "
	type("2E"
	assert(update() == "NORMAL 1,10-10 0% <0> "
	type("3E"
	assert(update() == "NORMAL 3,6-6 0% <0> "

nata.main(@ test("b moves count words backward", "abc() abc\t()\n\nabc", @(vi, type, update)
	assert(vi.buffer().view.position__(17, true
	assert(update() == "NORMAL 3,4-4 0% <0> "
	type("b"
	assert(update() == "NORMAL 3,1-1 0% <0> "
	type("b"
	assert(update() == "NORMAL 2,1-1 0% <0> "
	type("b"
	assert(update() == "NORMAL 1,11-11 0% <0> "
	type("b"
	assert(update() == "NORMAL 1,7-7 0% <0> "
	type("b"
	assert(update() == "NORMAL 1,4-4 0% <0> "
	type("b"
	assert(update() == "NORMAL 1,1-1 0% <0> "
	type("b"
	assert(update() == "NORMAL 1,1-1 0% <0> "
	assert(vi.buffer().view.position__(17, true
	assert(update() == "NORMAL 3,4-4 0% <0> "
	type("2b"
	assert(update() == "NORMAL 2,1-1 0% <0> "
	type("2b"
	assert(update() == "NORMAL 1,7-7 0% <0> "
	type("3b"
	assert(update() == "NORMAL 1,1-1 0% <0> "

nata.main(@ test("B moves count WORDS backward", "abc() abc\t()\n\n(abc)", @(vi, type, update)
	assert(vi.buffer().view.position__(19, false
	assert(update() == "NORMAL 3,6-6 0% <0> "
	type("B"
	assert(update() == "NORMAL 3,1-1 0% <0> "
	type("B"
	assert(update() == "NORMAL 2,1-1 0% <0> "
	type("B"
	assert(update() == "NORMAL 1,11-11 0% <0> "
	type("B"
	assert(update() == "NORMAL 1,7-7 0% <0> "
	type("B"
	assert(update() == "NORMAL 1,1-1 0% <0> "
	type("B"
	assert(update() == "NORMAL 1,1-1 0% <0> "
	assert(vi.buffer().view.position__(19, false
	assert(update() == "NORMAL 3,6-6 0% <0> "
	type("2B"
	assert(update() == "NORMAL 2,1-1 0% <0> "
	type("2B"
	assert(update() == "NORMAL 1,7-7 0% <0> "
	type("3B"
	assert(update() == "NORMAL 1,1-1 0% <0> "
