assert = @(x) x || throw Throwable("Assertion failed."
nata = Module("nata"
testing = Module("testing"
test = testing.test

nata.main(@ test("quit", null, @(vi, type, update)
	assert(update() == "NORMAL 1,1-1 100% <0> "
	type("Z"
	assert(update() == "NORMAL 1,1-1 100% <0> Z"
	type("Z"
	assert(update() === null

nata.main(@ test("undo & redo", "abc", @(vi, type, update)
	type("dlllphdhhp"
	assert(update() == "NORMAL 1,2-2 100% <4>* "
	assert(vi.buffer().text.slice(0, -1) == "cba"
	type("u"
	assert(update() == "NORMAL 1,1-1 100% <3|1>* "
	assert(vi.buffer().text.slice(0, -1) == "ba"
	type("u"
	assert(update() == "NORMAL 1,3-3 100% <2|2>* "
	assert(vi.buffer().text.slice(0, -1) == "bca"
	type("u"
	assert(update() == "NORMAL 1,3-3 100% <1|3>* "
	assert(vi.buffer().text.slice(0, -1) == "bc"
	type("u"
	assert(update() == "NORMAL 1,1-1 100% <0|4> "
	assert(vi.buffer().text.slice(0, -1) == "abc"
	type("^R"
	assert(update() == "NORMAL 1,1-1 100% <1|3>* "
	assert(vi.buffer().text.slice(0, -1) == "bc"
	type("^R"
	assert(update() == "NORMAL 1,4-4 100% <2|2>* "
	assert(vi.buffer().text.slice(0, -1) == "bca"
	type("^R"
	assert(update() == "NORMAL 1,2-2 100% <3|1>* "
	assert(vi.buffer().text.slice(0, -1) == "ba"
	type("^R"
	assert(update() == "NORMAL 1,2-2 100% <4>* "
	assert(vi.buffer().text.slice(0, -1) == "cba"
	type("3u"
	assert(update() == "NORMAL 1,3-3 100% <1|3>* "
	assert(vi.buffer().text.slice(0, -1) == "bc"
	type("2^R"
	assert(update() == "NORMAL 1,2-2 100% <3|1>* "
	assert(vi.buffer().text.slice(0, -1) == "ba"

nata.main(@ test("buffers", "foo", @(vi, type, update)
	type(":buffers^M"
	assert(update() == "buffers\n1 % \"foo\""
	assert(vi.buffer().text.slice(0, -1) == "foo"
	type(":edit bar^M"
	assert(vi.buffer().text.slice(0, -1) == "bar"
	type(":buffers^M"
	assert(update() == "buffers\n1   \"foo\"\n2 % \"bar\""
	type(":edit foo^M"
	assert(vi.buffer().text.slice(0, -1) == "foo"
	type(":buffers^M"
	assert(update() == "buffers\n1 % \"foo\"\n2   \"bar\""
	type(":quit^M"
	assert(vi.buffer().text.slice(0, -1) == "bar"
	type(":buffers^M"
	assert(update() == "buffers\n1 % \"bar\""
